import 'package:firebase_core/firebase_core.dart'; // Firebase Core
import 'package:flutter/material.dart';
import 'package:chat_us/screens/auth/login_sc.dart';
// import 'package:chat_us/screens/home_sc.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Configurations
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Lets Chat',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color.fromARGB(255, 98, 36, 205),
        ),
        useMaterial3: true,
      ),
      home: LoginScreen(),
      // home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
